image:
  name: sagemath/sagemath-dev:9.2
  entrypoint: [ "" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

test:
  tags:
    - shared-fi
  script:
    - export PATH=$PATH:`sage -c "import sys; import os; print(os.path.join([x for x in sys.path if 'src/bin' in x][0],'../../local/bin') + ':' + \":\".join(sys.path))" 2>/dev/null`
    - sage -i database_kohel
    - sage --python3 setup.py install
    - sage --python3 -m unittest discover dissect/unit_tests
