image:
  name: sagemath/sagemath:latest
  entrypoint: [""]

stages:
  - test

test:
  tags:
    - shared-fi
  before_script:
    - sage --pip3 install Ptable
  script:
    - export PATH=$PATH:`sage -c "import sys; print(\":\".join(sys.path))"`
    - sage --python3 setup.py install
    - sage --python3 -m unittest discover curve_analyzer/tests/unit_tests
